# Generated by Django 5.1.6 on 2025-02-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='done_date',
            new_name='done',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
